/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.digdag.plugin

import io.digdag.spi.Operator
import io.digdag.spi.OperatorContext
import io.digdag.spi.OperatorFactory
import io.digdag.spi.OperatorProvider
import io.digdag.spi.Plugin
import io.digdag.spi.TaskResult
import io.digdag.util.BaseOperator
import java.lang.Class

class AppConfigPlugin : Plugin {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-spi/src/main/java/io/digdag/spi/Plugin.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExamplePlugin.java
    override fun <T> getServiceProvider(type: Class<T>): Class<out T> {
        return AppConfigOperatorProvider::class.java.asSubclass(type)
    }
}

class AppConfigOperatorProvider : OperatorProvider {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-spi/src/main/java/io/digdag/spi/OperatorProvider.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExamplePlugin.java

    // @Inject
    // protected TemplateEngine templateEngine;
    override fun get(): List<OperatorFactory> = listOf(AppConfigOperatorFactory("appconfig"))
}

class AppConfigOperatorFactory(val operatorName: String) : OperatorFactory {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-spi/src/main/java/io/digdag/spi/OperatorFactory.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExampleOperatorFactory.java
    override fun getType(): String = operatorName
    override fun newOperator(ctx: OperatorContext): Operator = AppConfigOperator(ctx)
}

class AppConfigOperator(ctx: OperatorContext) : BaseOperator(ctx) {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-plugin-utils/src/main/java/io/digdag/util/BaseOperator.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExampleOperatorFactory.java
    override fun runTask(): TaskResult {
        println("$request")
        return TaskResult.empty(request)
    }
}
