/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.digdag.plugin

// import kotlin.test.Test
// import kotlin.test.assertTrue

class AppConfigPluginTest {
    // @Test fun testSomeLibraryMethod() {
    //     val classUnderTest = Library()
    //     assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    // }
}
