/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.digdag.plugin.aws.appconfig

// import io.digdag.plugin.aws.appconfig.params.Credentials
// import io.digdag.plugin.aws.appconfig.params.Resource
import io.digdag.plugin.aws.appconfig.module.service.AwsAppConfigService
import io.digdag.spi.Operator
import io.digdag.spi.OperatorContext
import io.digdag.spi.OperatorFactory
import io.digdag.spi.OperatorProvider
import io.digdag.spi.Plugin
import io.digdag.spi.TaskResult
import io.digdag.util.BaseOperator
import java.lang.Class

class AwsAppConfigPlugin : Plugin {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-spi/src/main/java/io/digdag/spi/Plugin.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExamplePlugin.java
    override fun <T> getServiceProvider(type: Class<T>): Class<out T> {
        return AwsAppConfigOperatorProvider::class.java.asSubclass(type)
    }
}

class AwsAppConfigOperatorProvider : OperatorProvider {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-spi/src/main/java/io/digdag/spi/OperatorProvider.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExamplePlugin.java

    // @Inject
    // protected TemplateEngine templateEngine;
    override fun get(): List<OperatorFactory> = listOf(AwsAppConfigOperatorFactory("aws.appconfig.get_configuration"))
}

class AwsAppConfigOperatorFactory(val operatorName: String) : OperatorFactory {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-spi/src/main/java/io/digdag/spi/OperatorFactory.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExampleOperatorFactory.java
    override fun getType(): String = operatorName
    override fun newOperator(ctx: OperatorContext): Operator = AwsAppConfigOperator(ctx)
}

class AwsAppConfigOperator(ctx: OperatorContext) : BaseOperator(ctx) {
    // Definition: https://github.com/treasure-data/digdag/blob/master/digdag-plugin-utils/src/main/java/io/digdag/util/BaseOperator.java
    // Example: https://github.com/myui/digdag-plugin-example/blob/master/src/main/java/io/digdag/plugin/example/ExampleOperatorFactory.java
    override fun runTask(): TaskResult {
        // val config = request.getConfig()
        // val credentials = Credentials.fromConfig(config.getNestedOrGetEmpty("credentials"))
        // val resource = Resource.fromConfig(config.getNested("resource"))
        // println("$credentials")
        // println("$resource")
        val a = AwsAppConfigService
        a.test("DITest1")
        val b = AwsAppConfigService.Mock
        b.test("DITest2")
        return TaskResult.empty(request)
    }
}
