/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.digdag.plugin.aws.appconfig.module.service

// import org.junit.jupiter.api.Assertions.assertEquals
// import org.junit.jupiter.api.Assertions.fail
import io.digdag.plugin.aws.appconfig.module.component.LoggerComponent
import io.digdag.plugin.aws.appconfig.module.repository.aws.AwsAppConfigRepository
import kotlin.test.Test
import kotlin.test.assertTrue

class AwsAppConfigServiceTest {

    interface RepoTestService :
        AwsAppConfigService,
        LoggerComponent.Provider

    @Test fun testSomeLibraryMethod() {
        val service = object : RepoTestService {
            override val awsAppConfigRepository: AwsAppConfigRepository =
                object : AwsAppConfigRepository {
                    override fun test(message: String) {
                        println("MockTest")
                    }
                }
        }
        service.test("aaaa")
        assertTrue(true)
    }
}
